version: '3'

services:

#  shop:
#    build:
#      context: shop
#    depends_on:
#      - shop_db
#      - events
#    environment:
#      DATABASE_HOST: shop_db
#      DATABASE_NAME: shob_db_store
#
#  shop_db:
#    image: mongo:3.7.3

  logistics_api:
    build: logistics/api
    depends_on:
      - logistics_db
      - events
    environment:
      DATABASE_HOST: logistics_db
      DATABASE_NAME: logistics_db_store
      RACK_ENV: production
    ports:
      - 9292:9292

  logistics_event_handler:
    build: logistics/event-handler
    depends_on:
      - logistics_api
      - events
    environment:
      LOGISTICS_API: http://logistics_api:9292
      REDIS_CONNECTION: redis://events:6379

  logistics_db:
    image: mongo:3.7.3
#
#  tracking:
#    build:
#      ./tracking
#    depends_on:
#      - tracking_db
#      - events
#    environment:
#      DATABASE_HOST: tracking_db
#      DATABASE_NAME: tracking_db_store
#
#  tracking_db:
#      image: mongo:3.7.3

  events:
    image: redis:3.2-alpine