version: '3.2'

services:

#  shop:
#    build:
#      context: shop
#    depends_on:
#      - shop_db
#      - events
#    environment:
#      DATABASE_HOST: shop_db
#      DATABASE_NAME: shob_db_store
#
#  shop_db:
#    image: mongo:3.7.3

  logistics_api:
    build: logistics/api
    depends_on:
      - logistics_db
      - events
    environment:
      DATABASE_HOST: logistics_db
      DATABASE_NAME: logistics_db_store
      RACK_ENV: production
    ports:
      - '9292:9292'

  logistics_event_handler:
    build: logistics/event-handler
    depends_on:
      - logistics_api
      - events
    restart: unless-stopped
    environment:
      LOGISTICS_API: http://logistics_api:9292
      RMQ_EVENT_LIST_CONNECTION: amqp://eventsDemoRMQUser:eventsDemoRMQPassword@events:5672

  logistics_db:
    image: mongo:3.7.3
#
#  tracking:
#    build:
#      ./tracking
#    depends_on:
#      - tracking_db
#      - events
#    environment:
#      << : *depends-on-events-queue-config
#
#  tracking_db:
#      image: mongo:3.7.3

  events:
    image: rabbitmq:3.7.4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: eventsDemoRMQUser
      RABBITMQ_DEFAULT_PASS: eventsDemoRMQPassword
    ports:
      - '15672:15672'