FROM ruby:2.5.1-alpine3.7

RUN apk update && apk add build-base

RUN mkdir /application
WORKDIR /application
ADD event-handler/Gemfile /application/Gemfile
ADD event-handler/Gemfile.lock /application/Gemfile.lock
RUN bundle install
ADD event-handler /application

CMD ruby main.rb